version: '3.7'
services:
  database01:
    image: postgres:12
    container_name: database01
    restart: always
    ports:
      - 3333:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql